# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SideMenu'
  pod 'SideMenu', :inhibit_warnings => true

  # Pods for NewsAPI

end
